name: sub_bagussh
description: A new Flutter application.

publish_to: 'none' 

environment:
  sdk: ">=2.16.1 <3.0.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  bloc_test: ^9.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.5.3

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  test: 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tvclil.png
    - certificates/    