// Mocks generated by Mockito 5.2.0 from annotations
// in sub_bagussh/test/presentation/bloc/tv/on_watchlist_tv_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sub_bagussh/common/failure.dart' as _i11;
import 'package:sub_bagussh/domain/entities/tvclil/tvclil.dart' as _i12;
import 'package:sub_bagussh/domain/entities/tvclil/tvclil_detail.dart' as _i13;
import 'package:sub_bagussh/domain/repositories/tvclil_repository.dart' as _i8;
import 'package:sub_bagussh/domain/usecases/tvclil/get_watchlist_status_tvclil.dart'
    as _i3;
import 'package:sub_bagussh/domain/usecases/tvclil/get_watchlist_tvclil.dart'
    as _i2;
import 'package:sub_bagussh/domain/usecases/tvclil/remove_watchlist_tvclil.dart'
    as _i5;
import 'package:sub_bagussh/domain/usecases/tvclil/save_watchlist_tvclil.dart'
    as _i4;
import 'package:sub_bagussh/presentation/bloc/tv/watchlist/tv_watchlist_bloc.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetWatchlistTvclil_0 extends _i1.Fake
    implements _i2.GetWatchlistTvclil {}

class _FakeGetWatchListStatusTvclil_1 extends _i1.Fake
    implements _i3.GetWatchListStatusTvclil {}

class _FakeSaveWatchlistTvclil_2 extends _i1.Fake
    implements _i4.SaveWatchlistTvclil {}

class _FakeRemoveWatchlistTvclil_3 extends _i1.Fake
    implements _i5.RemoveWatchlistTvclil {}

class _FakeTvWatchlistState_4 extends _i1.Fake implements _i6.TvWatchlistState {
}

class _FakeEither_5<L, R> extends _i1.Fake implements _i7.Either<L, R> {}

class _FakeTvclilRepository_6 extends _i1.Fake implements _i8.TvclilRepository {
}

/// A class which mocks [TvWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvWatchlistBloc extends _i1.Mock implements _i6.TvWatchlistBloc {
  MockTvWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistTvclil get getWatchlistTv =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistTv),
          returnValue: _FakeGetWatchlistTvclil_0()) as _i2.GetWatchlistTvclil);
  @override
  _i3.GetWatchListStatusTvclil get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListStatusTvclil_1())
          as _i3.GetWatchListStatusTvclil);
  @override
  _i4.SaveWatchlistTvclil get saveWatchlist => (super.noSuchMethod(
      Invocation.getter(#saveWatchlist),
      returnValue: _FakeSaveWatchlistTvclil_2()) as _i4.SaveWatchlistTvclil);
  @override
  _i5.RemoveWatchlistTvclil get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlistTvclil_3())
          as _i5.RemoveWatchlistTvclil);
  @override
  _i6.TvWatchlistState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeTvWatchlistState_4()) as _i6.TvWatchlistState);
  @override
  _i9.Stream<_i6.TvWatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.TvWatchlistState>.empty())
          as _i9.Stream<_i6.TvWatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.TvWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.TvWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.TvWatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.TvWatchlistEvent>(
          _i10.EventHandler<E, _i6.TvWatchlistState>? handler,
          {_i10.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i10.Transition<_i6.TvWatchlistEvent, _i6.TvWatchlistState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void onChange(_i10.Change<_i6.TvWatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetWatchlistTvclil].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvclil extends _i1.Mock
    implements _i2.GetWatchlistTvclil {
  MockGetWatchlistTvclil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Either<_i11.Failure, List<_i12.Tvclil>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i7.Either<_i11.Failure, List<_i12.Tvclil>>>.value(
                      _FakeEither_5<_i11.Failure, List<_i12.Tvclil>>()))
          as _i9.Future<_i7.Either<_i11.Failure, List<_i12.Tvclil>>>);
}

/// A class which mocks [GetWatchListStatusTvclil].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTvclil extends _i1.Mock
    implements _i3.GetWatchListStatusTvclil {
  MockGetWatchListStatusTvclil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.TvclilRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvclilRepository_6()) as _i8.TvclilRepository);
  @override
  _i9.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [RemoveWatchlistTvclil].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvclil extends _i1.Mock
    implements _i5.RemoveWatchlistTvclil {
  MockRemoveWatchlistTvclil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.TvclilRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvclilRepository_6()) as _i8.TvclilRepository);
  @override
  _i9.Future<_i7.Either<_i11.Failure, String>> execute(_i13.TvclilDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i7.Either<_i11.Failure, String>>.value(
                  _FakeEither_5<_i11.Failure, String>()))
          as _i9.Future<_i7.Either<_i11.Failure, String>>);
}

/// A class which mocks [SaveWatchlistTvclil].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvclil extends _i1.Mock
    implements _i4.SaveWatchlistTvclil {
  MockSaveWatchlistTvclil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.TvclilRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvclilRepository_6()) as _i8.TvclilRepository);
  @override
  _i9.Future<_i7.Either<_i11.Failure, String>> execute(_i13.TvclilDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i7.Either<_i11.Failure, String>>.value(
                  _FakeEither_5<_i11.Failure, String>()))
          as _i9.Future<_i7.Either<_i11.Failure, String>>);
}
