// Mocks generated by Mockito 5.2.0 from annotations
// in sub_bagussh/test/helpers/test_helper_movie_tvclil.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i26;

import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i16;
import 'package:sub_bagussh/common/failure.dart' as _i8;
import 'package:sub_bagussh/data/datasources/db/database_helper.dart' as _i24;
import 'package:sub_bagussh/data/datasources/db/database_helper_tvclil.dart'
    as _i15;
import 'package:sub_bagussh/data/datasources/movie/movie_local_data_source.dart'
    as _i22;
import 'package:sub_bagussh/data/datasources/movie/movie_remote_data_source.dart'
    as _i20;
import 'package:sub_bagussh/data/datasources/tvclil/tvclil_local_data_source.dart'
    as _i13;
import 'package:sub_bagussh/data/datasources/tvclil/tvclil_remote_data_source.dart'
    as _i11;
import 'package:sub_bagussh/data/models/movies/movie_detail_model.dart' as _i4;
import 'package:sub_bagussh/data/models/movies/movie_model.dart' as _i21;
import 'package:sub_bagussh/data/models/movies/movie_table.dart' as _i23;
import 'package:sub_bagussh/data/models/tvclil/tvclil_detail_model.dart' as _i3;
import 'package:sub_bagussh/data/models/tvclil/tvclil_model.dart' as _i12;
import 'package:sub_bagussh/data/models/tvclil/tvclil_table.dart' as _i14;
import 'package:sub_bagussh/domain/entities/movies/movie.dart' as _i18;
import 'package:sub_bagussh/domain/entities/movies/movie_detail.dart' as _i19;
import 'package:sub_bagussh/domain/entities/tvclil/tvclil.dart' as _i9;
import 'package:sub_bagussh/domain/entities/tvclil/tvclil_detail.dart' as _i10;
import 'package:sub_bagussh/domain/repositories/movie_repository.dart' as _i17;
import 'package:sub_bagussh/domain/repositories/tvclil_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeTvclilDetailResponse_1 extends _i1.Fake
    implements _i3.TvclilDetailResponse {}

class _FakeMovieDetailResponse_2 extends _i1.Fake
    implements _i4.MovieDetailResponse {}

class _FakeResponse_3 extends _i1.Fake implements _i5.Response {}

class _FakeStreamedResponse_4 extends _i1.Fake implements _i5.StreamedResponse {
}

/// A class which mocks [TvclilRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvclilRepository extends _i1.Mock implements _i6.TvclilRepository {
  MockTvclilRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> getNowPlayingTv() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTv, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> getTopRatedTv() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTv, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.TvclilDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, _i10.TvclilDetail>>.value(
              _FakeEither_0<_i8.Failure, _i10.TvclilDetail>())) as _i7
          .Future<_i2.Either<_i8.Failure, _i10.TvclilDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> searchTv(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlistTv(
          _i10.TvclilDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlistTv(
          _i10.TvclilDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToWatchlistTv(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlistTv, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Tvclil>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Tvclil>>>);
}

/// A class which mocks [TvclilRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvclilRemoteDataSource extends _i1.Mock
    implements _i11.TvclilRemoteDataSource {
  MockTvclilRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i12.TvclilModel>> getNowPlayingTv() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTv, []),
              returnValue:
                  Future<List<_i12.TvclilModel>>.value(<_i12.TvclilModel>[]))
          as _i7.Future<List<_i12.TvclilModel>>);
  @override
  _i7.Future<List<_i12.TvclilModel>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
              returnValue:
                  Future<List<_i12.TvclilModel>>.value(<_i12.TvclilModel>[]))
          as _i7.Future<List<_i12.TvclilModel>>);
  @override
  _i7.Future<List<_i12.TvclilModel>> getTopRatedTv() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTv, []),
              returnValue:
                  Future<List<_i12.TvclilModel>>.value(<_i12.TvclilModel>[]))
          as _i7.Future<List<_i12.TvclilModel>>);
  @override
  _i7.Future<_i3.TvclilDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: Future<_i3.TvclilDetailResponse>.value(
                  _FakeTvclilDetailResponse_1()))
          as _i7.Future<_i3.TvclilDetailResponse>);
  @override
  _i7.Future<List<_i12.TvclilModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue:
                  Future<List<_i12.TvclilModel>>.value(<_i12.TvclilModel>[]))
          as _i7.Future<List<_i12.TvclilModel>>);
  @override
  _i7.Future<List<_i12.TvclilModel>> searchTv(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
              returnValue:
                  Future<List<_i12.TvclilModel>>.value(<_i12.TvclilModel>[]))
          as _i7.Future<List<_i12.TvclilModel>>);
}

/// A class which mocks [TvclilLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvclilLocalDataSource extends _i1.Mock
    implements _i13.TvclilLocalDataSource {
  MockTvclilLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlistTv(_i14.TvclilTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlistTv, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeWatchlistTv(_i14.TvclilTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTv, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i14.TvclilTable?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<_i14.TvclilTable?>.value())
          as _i7.Future<_i14.TvclilTable?>);
  @override
  _i7.Future<List<_i14.TvclilTable>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue:
                  Future<List<_i14.TvclilTable>>.value(<_i14.TvclilTable>[]))
          as _i7.Future<List<_i14.TvclilTable>>);
}

/// A class which mocks [DatabaseHelperTvclil].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelperTvclil extends _i1.Mock
    implements _i15.DatabaseHelperTvclil {
  MockDatabaseHelperTvclil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i16.Database?> get databasetvclil =>
      (super.noSuchMethod(Invocation.getter(#databasetvclil),
              returnValue: Future<_i16.Database?>.value())
          as _i7.Future<_i16.Database?>);
  @override
  _i7.Future<int> insertWatchlistTv(_i14.TvclilTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlistTv, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeWatchlistTv(_i14.TvclilTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTv, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i17.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i19.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, _i19.MovieDetail>>.value(
              _FakeEither_0<_i8.Failure, _i19.MovieDetail>())) as _i7
          .Future<_i2.Either<_i8.Failure, _i19.MovieDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
          _i19.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
          _i19.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i20.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i21.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  Future<List<_i21.MovieModel>>.value(<_i21.MovieModel>[]))
          as _i7.Future<List<_i21.MovieModel>>);
  @override
  _i7.Future<List<_i21.MovieModel>> getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue: Future<List<_i21.MovieModel>>.value(<_i21.MovieModel>[]))
      as _i7.Future<List<_i21.MovieModel>>);
  @override
  _i7.Future<List<_i21.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
          Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<List<_i21.MovieModel>>.value(<_i21.MovieModel>[]))
      as _i7.Future<List<_i21.MovieModel>>);
  @override
  _i7.Future<_i4.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i4.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_2()))
          as _i7.Future<_i4.MovieDetailResponse>);
  @override
  _i7.Future<List<_i21.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i21.MovieModel>>.value(<_i21.MovieModel>[]))
          as _i7.Future<List<_i21.MovieModel>>);
  @override
  _i7.Future<List<_i21.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  Future<List<_i21.MovieModel>>.value(<_i21.MovieModel>[]))
          as _i7.Future<List<_i21.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i22.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i23.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i23.MovieTable?>.value())
          as _i7.Future<_i23.MovieTable?>);
  @override
  _i7.Future<List<_i23.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
          Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<List<_i23.MovieTable>>.value(<_i23.MovieTable>[]))
      as _i7.Future<List<_i23.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i24.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i16.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i16.Database?>.value())
          as _i7.Future<_i16.Database?>);
  @override
  _i7.Future<int> insertWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i26.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i26.Uint8List>.value(_i26.Uint8List(0)))
          as _i7.Future<_i26.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4()))
          as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
